import { VercelRequest, VercelResponse } from '@vercel/node';
import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  try {
    const { planData, userDetails } = req.body;

    if (!planData || !userDetails) {
      return res.status(400).json({ message: 'Missing plan data or user details' });
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="ZenThira_Growth_Plan.pdf"');

    const doc = new PDFDocument({ 
      margin: 50,
      size: 'A4',
      bufferPages: true 
    });

    doc.pipe(res);

    const primaryColor = '#a855f7'; // Purple Theme
    const darkColor = '#0a0a0a';
    const textColor = '#333333';
    const lightGray = '#f0f0f0';

    // Helper to format text
    const cleanText = (text: any) => {
      if (!text) return "";
      
      const parseValue = (val: any, depth = 0): string => {
        if (typeof val === 'string') {
          val = val.trim();
          if ((val.startsWith('{') && val.endsWith('}')) || (val.startsWith('[') && val.endsWith(']'))) {
            try { val = JSON.parse(val); } catch(e) {}
          }
        }
        
        const indent = " ".repeat(depth * 2);
        if (Array.isArray(val)) {
          return val.map(item => `${indent}• ${parseValue(item, 0)}`).join('\n');
        }
        if (typeof val === 'object' && val !== null) {
          return Object.entries(val)
            .map(([k, v]) => `${indent}• ${k.toUpperCase()}:\n${parseValue(v, depth + 1)}`)
            .join('\n\n');
        }
        return String(val).replace(/\*\*/g, '').replace(/\*/g, '');
      };

      return parseValue(text).trim();
    };

    // Header Background
    doc.rect(0, 0, doc.page.width, 100).fill(darkColor);
    
    // Logo / Title
    try {
      doc.image('src/assest/LYKSPIRE LOGO.png', 50, 25, { width: 50 });
      doc.fontSize(24).fillColor(primaryColor).font('Times-Bold')
         .text('LyKSpire', 110, 35);
      doc.fontSize(12).fillColor('#ffffff').font('Times-Roman')
         .text('Custom Growth & Automation Strategy', 110, 63);
    } catch(e) {
      doc.fontSize(24).fillColor(primaryColor).font('Times-Bold')
         .text('LyKSpire', 50, 40);
      doc.fontSize(12).fillColor('#ffffff').font('Times-Roman')
         .text('Custom Growth & Automation Strategy', 50, 68);
    }

    doc.moveDown(4);

    // Client Details Section
    doc.rect(50, 120, doc.page.width - 100, 50).fill(lightGray);
    doc.fontSize(14).fillColor(darkColor).font('Times-Bold')
       .text('Prepared For:', 65, 135);
    doc.fontSize(12).font('Times-Roman')
       .text(`Email: ${userDetails.email} | Phone: ${userDetails.phone}`, 65, 155);

    doc.moveDown(3);

    // Function to render section box without causing empty pages
    const renderSection = (title: string, content: any) => {
      const cleaned = cleanText(content);
      if (!cleaned) return;
      
      doc.moveDown(1.5);
      
      // Section Title (Text only to prevent rect pagination bugs)
      doc.fontSize(16).fillColor(primaryColor).font('Times-Bold')
         .text(title, 50, doc.y);
      
      doc.moveDown(0.5);
      
      // Content
      doc.fontSize(11).fillColor(textColor).font('Times-Roman')
         .text(cleanText(content), 50, doc.y, {
           align: 'left',
           lineGap: 4,
           width: doc.page.width - 100
         });
    };

    renderSection("1. Business Overview", planData.businessOverview);
    renderSection("2. AI Solutions & Automation Plan", planData.automationPlan);
    renderSection("3. Future Growth & Enhancements", planData.futureGrowth);

    // Add footer and page numbers on all pages
    const range2 = doc.bufferedPageRange();
    const totalPages = range2.count;
    for (let i = range2.start; i < range2.start + totalPages; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 40;
      
      // Footer Line
      doc.rect(50, footerY - 10, doc.page.width - 100, 1).fill('#dddddd');
      
      // Footer text - absolute coords, lineBreak: false prevents cursor overflow
      doc.fontSize(9).fillColor('#888888').font('Helvetica')
         .text('Generated by LyKSpire | Confidential Strategy Document', 50, footerY, { lineBreak: false });
         
      // Page Number
      doc.fontSize(9).fillColor('#888888').font('Helvetica')
         .text(`Page ${i + 1} of ${totalPages}`, 0, footerY, { align: 'right', lineBreak: false, width: doc.page.width - 50 });
    }

    // CRITICAL: Reset cursor to safe Y after switchToPage loop
    // Without this, PDFKit sees cursor at bottom and creates a blank overflow page
    doc.switchToPage(range2.start + totalPages - 1);
    doc.y = 100;

    doc.end();

  } catch (error) {
    console.error('Error generating PDF:', error);
    if (!res.headersSent) {
      return res.status(500).json({ message: 'Internal Server Error' });
    }
  }
}
